### PR TITLE
Fix zombie processes created by FullTeaching test suite

### LINKED ISSUE #135: Flaky Regressions due to reach the max number of threads with FullTeaching test suite
A couple of days ago, we encountered a failure during the update process. The failure occurred due to an issue instantiating a new thread in Maven Surefire. Before starting the debugging process, I noticed a significant number of zombie processes in our virtual machine:

Zombie Processes

These processes originated from the JDK of the Jenkins slave:

JDK Jenkins Slave

#### Jenkins Trace Log
The test execution was unable to create the log file, but the content of the Jenkins trace is as follows:

```log
+ /home/jenkins/workspace/retorch-st-fullteaching_main/retorchfiles/scripts/tjoblifecycles/tjob-testexecution.sh tjobn 2 https://full-teaching-/ 5000 'FullTeachingEndToEndRESTTests#sessionRestOperations'
Using the provided URL
The URL IS https://full-teaching-/
The HOST_IP is: 172.22.0.1 and PORT 5000 for the TJOB tjobn
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< com.fullteaching:e2e.no-elastest >------------------
[INFO] Building com.fullteaching:e2e.no-elastest 1.1.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ e2e.no-elastest ---
[INFO] skip non existing resourceDirectory /home/jenkins/workspace/retorch-st-fullteaching_main/src/main/resources
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ e2e.no-elastest ---
[INFO] Nothing to compile - all classes are up to date.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ e2e.no-elastest ---
[INFO] Copying 6 resources from src/test/resources to target/test-classes
[INFO] 
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ e2e.no-elastest ---
[INFO] Nothing to compile - all classes are up to date.
[INFO] 
[INFO] --- jacoco:0.8.12:prepare-agent (jacoco-initialize) @ e2e.no-elastest ---
[INFO] argLine set to -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/home/jenkins/workspace/retorch-st-fullteaching_main/target/coverage-reports/jacoco-unit.exec,append=true,excludes=*MethodAccess,output=file
[INFO] 
[INFO] --- surefire:3.3.1:test (default-test) @ e2e.no-elastest ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] Unable to create test class 'com.fullteaching.e2e.no_elastest.functional.test.media.FullTeachingEndToEndRESTTests'
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.858 s
[INFO] Finished at: 2024-07-29T11:54:46+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.1:test (default-test) on project e2e.no-elastest: 
[ERROR] 
[ERROR] Please refer to /home/jenkins/workspace/retorch-st-fullteaching_main/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Unable to create test class 'com.fullteaching.e2e.no_elastest.functional.test.media.FullTeachingEndToEndRESTTests'
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Unable to create test class 'com.fullteaching.e2e.no_elastest.functional.test.media.FullTeachingEndToEndRESTTests'
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1256)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1105)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:939)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### PR DESCRIPTION
**Pull request by augustocristian**
This PR is related to #52 and closes #135, solves the remaining problem with the zombie processes, and improves the suite's maintainability and understability.
Contains the following improvements:
- Now all test cases are parametrized and use common methods that set-up and tear-down the browsers and configuration files.
- The second user and student drivers are managed globally, tearing down them when are used in the Chat-videocall cases.
- replyToComment test, previosusly @Disabled and now enabled and passing
- Minor improvements suggested by Lint (e.g reemplace size()==0 by isEmpty()) and some rename of variables in the files that we modify.

### CODE REVIEW

File: src/test/java/com/fullteaching/e2e/no_elastest/common/BaseLoggedTest.java [hunk 1]
```diff
@@ -66,7 +66,7 @@ static void setupAll() { // 28 lines
             // Load a properties file for reading
             properties.load(new FileInputStream("src/test/resources/inputs/test.properties"));
         } catch (IOException ex) {
-            ex.printStackTrace(); // Consider logging the exception instead of printing the stack trace
+            log.error("Properties file could not be loaded");
```
Comment (javiertuya) [inline src/test/java/com/fullteaching/e2e/no_elastest/common/BaseLoggedTest.java:69]: As I understand, the test.properties file is a requirement to run the tests. If it can't be loaded, the test should fail

File: src/test/java/com/fullteaching/e2e/no_elastest/common/BaseLoggedTest.java [hunk 2]
```diff
@@ -224,19 +243,21 @@ private void login(BrowserUser user, String userEmail, String userPass,
         try {
             userName = getUserName(user, true, APP_URL);
         } catch (NotLoggedException | ElementNotFoundException e) {
-            // TODO Auto-generated catch block
-            e.printStackTrace();
+            if (e.getClass().isInstance(NotLoggedException.class)){
+            log.error("The user {} was not logged",user.getClientData());}
+            else{
+                log.error("The userName field not found" );
+            }
```
Comment (javiertuya) [inline src/test/java/com/fullteaching/e2e/no_elastest/common/BaseLoggedTest.java:250]: Shouldn't this make the test fail?

On the other hand, is it really necesary to control the exceptions? There are two diffferent named exceptions, each represents a cause of failure, what if execute `userName = getUserName(user, true, APP_URL);` without any exception control, and let JUnit control the exceptions to fail the test with an error?

File: src/test/java/com/fullteaching/e2e/no_elastest/common/BaseLoggedTest.java [hunk 3]
```diff
@@ -347,7 +368,7 @@ protected void waitSeconds(int seconds) {
         try {
             Thread.sleep(1000L * seconds);
         } catch (InterruptedException e) {
-            e.printStackTrace();
+            log.error("Thread.sleep interrupted");
```
Comment (javiertuya) [inline src/test/java/com/fullteaching/e2e/no_elastest/common/BaseLoggedTest.java:371]: It is not frequent to have exceptions when doing a sleep, but, why this does not fails the test?

File: src/test/java/com/fullteaching/e2e/no_elastest/common/EdgeUser.java [hunk 4]
```diff
@@ -51,42 +50,31 @@ public EdgeUser(String userName, int timeOfWaitInSeconds, String testName, Strin
...
-                selenoidOptions.put("logName ", logName);
-                selenoidOptions.put("videoName", videoName);
-
+                selenoidOptions.put("logName ", String.format("%s%s",baseName.replaceAll("\\s","") , ".log"));
+                selenoidOptions.put("videoName", String.format("%s%s",baseName.replaceAll("\\s","") ,".mp4"));
                 selenoidOptions.put("screenResolution", "1920x1080x24");
-
                 options.setCapability("selenoid:options", selenoidOptions);
-
                 //END CAPABILITIES FOR SELENOID RETORCH
```
Comment (javiertuya) [inline src/test/java/com/fullteaching/e2e/no_elastest/common/EdgeUser.java:72]: This part of selenoid options seems to appear three times, it should be refactored, perhaps in the base class.
Do not do this now, create a new issue for it and annotate the number by replying this comment.

Note: Maybe there are more lines of code that are repeated, e.g. before this commented block.

File: src/test/java/com/fullteaching/e2e/no_elastest/functional/test/LoggedLinksTests.java [hunk 5]
```diff
@@ -21,39 +19,42 @@
...
 import static org.junit.jupiter.api.Assertions.assertTrue;
-import static org.slf4j.LoggerFactory.getLogger;
 
-@ExtendWith(SeleniumJupiter.class)
 class LoggedLinksTests extends BaseLoggedTest {
 
 
 
+
+
```
Comment (javiertuya) [inline src/test/java/com/fullteaching/e2e/no_elastest/functional/test/LoggedLinksTests.java:29]: There was three blank lines that should be only one, and you have added two more. This is common in this class.

File: src/test/java/com/fullteaching/e2e/no_elastest/functional/test/UserTest.java [hunk 6]
```diff
@@ -34,22 +35,23 @@ public static Stream<Arguments> data() throws IOException {
...
             assertTrue(true, "not logged");
         } catch (NotLoggedException | BadUserException e) {
-            e.printStackTrace();
+            log.debug("The user was not logged");
             fail("Not logged");
         } catch (ElementNotFoundException e) {
-            e.printStackTrace();
+            log.debug("The web element used to check the log was not found");
             fail(e.getLocalizedMessage());
         }
```
Comment (javiertuya) [inline src/test/java/com/fullteaching/e2e/no_elastest/functional/test/UserTest.java:56]: Check a previous comment, maybe there is no need to handle exceptions here

**Review by javiertuya — COMMENTED** [review]
This PR is mixing too many things, and the goal was to fix a problem, not to refactor all tests. Please DO NOT SUBMIT THIS KIND OF PRs again.

Main issues:
- duplicated code
- handling of exceptions in tests

File: src/test/java/com/fullteaching/e2e/no_elastest/common/EdgeUser.java (hunk 4 above)
Comment (augustocristian) [reply src/test/java/com/fullteaching/e2e/no_elastest/common/EdgeUser.java:72]: Done, created issue #146 with a associated branch from this PR

**Comment by augustocristian** [comment]
Sorry for including a lot of changes in this PR @javiertuya. When I started to look for the problem with the zombie processes, I found several main causes, so I addressed all:
- Have a set-up method in the parent  method and in the ones that inheritance 
- Not use correctly try with resources
- Not use DriverFactories and release the driver correctly.
- The issue with the agent, that probably was my blame because originally I changed the way that you introduced to me to deploy the agent (using the docker command) to a docker-compose.
So I tried to manage all  and try to include in the same PR the changes to resolve the problem.
The last commits have removed most of the exceptions from the test suite (was a common practice, I don't know if it was due to the non-expertise of the original developer) and removed the two-blank lines. I think that a complete refactoring of the code is needed also, but It implies to move-remove code, and it should introduce noise to the PR.

File: src/test/java/com/fullteaching/e2e/no_elastest/common/EdgeUser.java (hunk 4 above)
Comment (augustocristian) [reply src/test/java/com/fullteaching/e2e/no_elastest/common/EdgeUser.java:72]: Addressed in  https://github.com/giis-uniovi/retorch-st-fullteaching/tree/146-reduce-the-duplicated-code-in-base-chrome-edge-firefoxuser

**Comment by javiertuya** [comment]
@augustocristian Some after-merge comments:
- When removing some statements that make an inner block (e.g. if removing a try cach), it is acceptable to temporarily keep the original indentation if the block is large, so that, the changes that are shown in the PR reflect exactly the part of code that was removed. However, if the block is small, I thing that it would be better to correct the indentation of the block.
- I've seen many statements with an inline comment that computes the number of lines or says anything else. These comments must be removed, eg. 
```
            CourseNavigationUtilities.go2Tab(driver, HOME_ICON);//4 lines
            CourseNavigationUtilities.go2Tab(driver, SESSION_ICON);//4lines
            CourseNavigationUtilities.go2Tab(driver, FORUM_ICON);//4lines
            CourseNavigationUtilities.go2Tab(driver, FILES_ICON);//4lines
            CourseNavigationUtilities.go2Tab(driver, ATTENDERS_ICON);//4lines
```
